import {
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaChartBar,
  FaCalendarAlt,
  FaBlog,
  FaUsers,
  FaTools,
  FaCalendarCheck,
  FaHistory,
} from "react-icons/fa";
import React from "react";
import { TServiceTypeToDisplay } from "./types";
import { id } from "date-fns/locale";

export const userLinks = [
  { text: "Prihlásenie", path: "/prihlasenie" },
  { text: "Registrácia", path: "/registracia" },
] as const;

export const socialMediaLinks = [
  {
    icon: React.createElement(FaFacebook),
    path: "https://www.facebook.com/",
  },
  {
    icon: React.createElement(FaYoutube),
    path: "https://www.youtube.com/",
  },
  {
    icon: React.createElement(FaInstagram),
    path: "https://www.instagram.com/",
  },
] as const;

export const contactInfo = {
  companyName: "Meno firmy s.r.o.",
  name: "Marek Šútora",
  email: "marek.sutora@gmail.com",
  telephoneNumber: "+421 123 456 789",
  address: "P. Sherman, 42 Wallaby Way",
  zip: "958 03",
  city: "Sydney",
} as const;

export const dashboardLinks = {
  admin: [
    {
      text: "Štatistiky",
      path: "/dashboard/admin/statistiky",
      icon: React.createElement(FaChartBar),
    },
    {
      text: "Termíny",
      subMenuItems: [
        { text: "Nový termín", path: "/dashboard/admin/terminy/novy-termin" },
        {
          text: "Zarezervované termíny",
          path: "/dashboard/admin/terminy/zarezervovane-terminy",
        },
        {
          text: "História",
          path: "/dashboard/admin/terminy/historia",
        },
      ],
      icon: React.createElement(FaCalendarAlt),
    },
    {
      text: "Blog",
      subMenuItems: [
        { text: "Nový článok", path: "/dashboard/admin/blog/novy-clanok" },
        { text: "Všetky články", path: "/dashboard/admin/blog/vsetky-clanky" },
      ],
      icon: React.createElement(FaBlog),
    },
    {
      text: "Klienti",
      path: "/dashboard/admin/klienti",
      icon: React.createElement(FaUsers),
    }
    // ,{
    //   text: "Služby",
    //   path: "/dashboard/admin/sluzby",
    //   icon: React.createElement(FaTools),
    // },
  ],
  client: [
    {
      text: "Rezervácia",
      path: "/dashboard/klient/rezervacia",
      icon: React.createElement(FaCalendarCheck),
    },
    {
      text: "História",
      path: "/dashboard/klient/historia",
      icon: React.createElement(FaHistory),
    },
    {
      text: "Zarezerované termíny",
      path: "/dashboard/klient/zarezervovane-terminy",
      icon: React.createElement(FaCalendarAlt),
    },
  ],
};

export const serviceTypesToDisplay = [
  { 
    name: "Manuálna terapia",
    description: "Manuálna terapia je špecializovaná forma fyzikálnej terapie poskytovaná zručnými terapeutmi, ktorí používajú svoje ruky na aplikáciu tlaku na svalové tkanivo a manipuláciu s kĺbmi. Tento prístup zameraný na dotyk má za cieľ znížiť bolesť, zvýšiť rozsah pohybu a zlepšiť celkovú funkciu. Medzi bežne používané techniky patria mobilizácia mäkkých tkanív, mobilizácia kĺbov a myofasciálne uvoľňovanie. Manuálna terapia je účinná pri liečbe rôznych stavov, ako je bolesť chrbta, bolesť krku a športové zranenia. Zameriava sa na obnovenie pohybu a funkcie pohybového systému. Terapia často zahŕňa personalizovaný liečebný plán prispôsobený špecifickým potrebám a fyzickému stavu jednotlivca.",
    slug: "manualna-terapia",
    hexColor: "#92A758",
    stdcs: [
      { id: 1, durationMinutes: 35, cost: 45 },
      { id: 2, durationMinutes: 40, cost: 60 },
    ],
    imageUrl: "/manual-therapy.webp",
    iconName: "FaDiagnoses",
  },
  { 
    name: "Vstupná diagnostika",
    slug: "vstupna-diagnostika",
    description: "Vstupná diagnostika zahŕňa klinické vyšetrenie, pri ktorom fyzioterapeut hodnotí pacienta vykonávajúceho rôzne pohyby a strečingy. Miestnosť je vybavená diagnostickými nástrojmi, ako je goniometer, anatomické grafy a počítač na zaznamenávanie údajov. Terapeut si robí poznámky na klipbord a pozoruje pacientovu postúru a pohyby. Prostredie je profesionálne a dobre organizované, s plagátmi ľudského pohybového aparátu na stenách a blízko umiestneným liečebným stolom. Celková atmosféra je zameraná na klinické hodnotenie a presnú diagnostiku.",
    hexColor: "#4f519c",
    stdcs: [
      { id: 3, durationMinutes: 45, cost: 60 },
    ],
    imageUrl: "/assesment.webp",
    iconName: "FaClipboard",
  },
  { 
    name: "Bankovanie",
    slug: "bankovanie",
    description: "Bankovanie je terapeutická metóda, ktorá sa vykonáva v pokojnom prostredí terapii. Miestnosť je mäkko osvetlená prirodzeným svetlom a zdobená upokojujúcimi prvkami ako sú črepníkové rastliny a difúzory éterických olejov. Pacient leží tvárou nadol na masážnom stole a na chrbte má niekoľko sklenených pohárov. Terapeut používa plameň na vytvorenie vákua v jednom z pohárov pred jeho umiestnením na pokožku pacienta. V pozadí sú viditeľné police s úhľadne usporiadanými uterákmi a terapeutickými nástrojmi. Celková atmosféra je pokojná a prispieva k relaxácii a liečeniu.",
    hexColor: "#666699",
    stdcs: [
      { id: 5, durationMinutes: 30, cost: 25 },
    ],
    imageUrl: "/bank.webp",
    iconName: "FaHeart",
  },
  { 
    name: "Cvičenie",
    slug: "cvicenie",
    description: "Cvičenie je kľúčovým prvkom fyzioterapie, zameraným na zlepšenie fyzickej kondície, sily, flexibility a celkového zdravia. Počas fyzioterapeutických relácií sa pacienti učia správne techniky vykonávania rôznych cvikov, ktoré sú špecificky navrhnuté na riešenie ich individuálnych potrieb a zdravotných problémov. Terapeut poskytuje podrobný návod a spätnú väzbu, aby zabezpečil, že cviky sú vykonávané správne a bezpečne. Pacienti sa naučia, ako správne držať telo, ako posilniť slabé svalové skupiny, ako zlepšiť rozsah pohybu a ako predchádzať zraneniam. Tieto zručnosti im pomáhajú nielen počas terapie, ale aj v každodennom živote, čím prispievajú k dlhodobému zdraviu a pohode.",
    hexColor: "#993333",
    stdcs: [
      { id: 6, durationMinutes: 60, cost: 55 },
      { id: 7, durationMinutes: 45, cost: 50 },
    ],
    imageUrl: "/exercise.webp",
    iconName: "FaDumbbell",
  },
] as const;
  


export const PrimeReactLocaleSk = {
  startsWith: "Začína na",
  contains: "Obsahuje",
  notContains: "Neobsahuje",
  endsWith: "Končí na",
  equals: "Rovná sa",
  notEquals: "Nerovná sa",
  noFilter: "Bez filtra",
  filter: "Filter",
  lt: "Menšie než",
  lte: "Menšie než alebo rovné",
  gt: "Väčšie než",
  gte: "Väčšie než alebo rovné",
  dateIs: "Dátum je",
  dateIsNot: "Dátum nie je",
  dateBefore: "Dátum je pred",
  dateAfter: "Dátum je po",
  custom: "Vlastné",
  clear: "Vyčistiť",
  apply: "Použiť",
  matchAll: "Zodpovedá všetkým",
  matchAny: "Zodpovedá akémukoľvek",
  addRule: "Pridať pravidlo",
  removeRule: "Odstrániť pravidlo",
  accept: "Áno",
  reject: "Nie",
  choose: "Vybrať",
  upload: "Nahrať súbor",
  cancel: "Zrušiť",
  completed: "Dokončené",
  pending: "Čakajúce",
  fileSizeTypes: ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
  dayNames: [
    "Nedeľa",
    "Pondelok",
    "Utorok",
    "Streda",
    "Štvrtok",
    "Piatok",
    "Sobota",
  ],
  dayNamesShort: ["Ned", "Pon", "Uto", "Str", "Štv", "Pia", "Sob"],
  dayNamesMin: ["Ne", "Po", "Ut", "St", "Št", "Pi", "So"],
  monthNames: [
    "Január",
    "Február",
    "Marec",
    "Apríl",
    "Máj",
    "Jún",
    "Júl",
    "August",
    "September",
    "Október",
    "November",
    "December",
  ],
  monthNamesShort: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Máj",
    "Jún",
    "Júl",
    "Aug",
    "Sep",
    "Okt",
    "Nov",
    "Dec",
  ],
  chooseYear: "Vyberte rok",
  chooseMonth: "Vyberte mesiac",
  chooseDate: "Vyberte dátum",
  prevDecade: "Predchádzajúce desaťročie",
  nextDecade: "Nasledujúce desaťročie",
  prevYear: "Predchádzajúci rok",
  nextYear: "Nasledujúci rok",
  prevMonth: "Predchádzajúci mesiac",
  nextMonth: "Nasledujúci mesiac",
  prevHour: "Predchádzajúca hodina",
  nextHour: "Nasledujúca hodina",
  prevMinute: "Predchádzajúca minúta",
  nextMinute: "Nasledujúca minúta",
  prevSecond: "Predchádzajúca sekunda",
  nextSecond: "Nasledujúca sekunda",
  am: "ráno",
  pm: "popoludní",
  today: "Dnes",
  now: "Teraz",
  weekHeader: "Týž.",
  firstDayOfWeek: 1,
  showMonthAfterYear: false,
  dateFormat: "dd.mm.rrrr",
  weak: "Slabé",
  medium: "Stredné",
  strong: "Silné",
  passwordPrompt: "Zadejte heslo",
  emptyFilterMessage: "Neboli nájdené žiadne výsledky",
  searchMessage: "Je k dispozícií {0} výsledkov",
  selectionMessage: "Vybraných {0} položiek",
  emptySelectionMessage: "Žiadna vybraná položka",
  emptySearchMessage: "Neboli nájdené žiadne výsledky",
  emptyMessage: "Žiadne dostupné možnosti",
  aria: {
    trueLabel: "Pravda",
    falseLabel: "Nepravda",
    nullLabel: "Nevybrané",
    star: "1 hviezda",
    stars: "{star} hviezd",
    selectAll: "Všetky položky vybrané",
    unselectAll: "Všetky položky zrušené",
    close: "Zavrieť",
    previous: "Predchádzajúci",
    next: "Ďalší",
    navigation: "Navigácia",
    scrollTop: "Posunúť hore",
    moveTop: "Presunúť hore",
    moveUp: "Presunúť hore",
    moveDown: "Presunúť dole",
    moveBottom: "Presunúť dole",
    moveToTarget: "Presunúť na cieľ",
    moveToSource: "Presunúť ku zdroju",
    moveAllToTarget: "Presunúť všetko na cieľ",
    moveAllToSource: "Presunúť všetko ku zdroju",
    pageLabel: "{page}",
    firstPageLabel: "Prvá strana",
    lastPageLabel: "Posledná strana",
    nextPageLabel: "Dalšia strana",
    previousPageLabel: "Predchádzajúca strana",
    rowsPerPageLabel: "Riadkov na stranu",
    jumpToPageDropdownLabel: "Prejsť na stránku Dropdown",
    jumpToPageInputLabel: "Prejsť na stránku Input",
    selectRow: "Vybrať riadok",
    unselectRow: "Zrušiť výber riadku",
    expandRow: "Rozbaliť riadok",
    collapseRow: "Zbaliť riadok",
    showFilterMenu: "Zobraziť filter menu",
    hideFilterMenu: "Skryť filter menu",
    filterOperator: "Operátor filtra",
    filterConstraint: "Obmedzenie filtra",
    editRow: "Upraviť riadok",
    saveEdit: "Uložiť úpravu",
    cancelEdit: "Zrušiť úpravu",
    listView: "Zobrazenie zoznamu",
    gridView: "Zobrazenie mriežky",
    slide: "Snímka",
    slideNumber: "{slideNumber}",
    zoomImage: "Priblížiť obrázok",
    zoomIn: "Priblížiť",
    zoomOut: "Oddialiť",
    rotateRight: "Otočiť doprava",
    rotateLeft: "Otočiť doľava",
  },
} as const;


export const SlovakMonths = [
  "Január",
  "Február",
  "Marec",
  "Apríl",
  "Máj",
  "Jún",
  "Júl",
  "August",
  "September",
  "Október",
  "November",
  "December",
] as const;
